version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:15"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
